const cities = [
    "Amsterdam",
    "Athens",
    "Barcelona",
    "Berlin",
    "Bern",
    "Bratislava",
    "Brussels",
    "Budapest",
    "Copenhagen",
    "Edinburgh",
    "Helsinki",
    "Krakow",
    "Lisbon",
    "Ljubljana",
    "London",
    "Luxembourg",
    "Madrid",
    "Malta",
    "Milan",
    "Munich",
    "Oslo",
    "Paris",
    "Prague",
    "Riga",
    "Rome",
    "Salzburg",
    "Santorini",
    "Stockholm",
    "Tallinn",
    "Valletta",
    "Venice",
    "Vienna",
    "Vilnius",
    "Warsaw",
    "Zagreb",
    "Amalfi",
    "Belfast",
    "Bergen",
    "Bordeaux",
    "Cologne",
    "Dubrovnik",
    "Florence",
    "Geneva",
    "Glasgow",
    "Innsbruck",
    "Nice",
    "Split",
    "Zurich",
    "Abu Dhabi",
    "Auckland",
    "Bangkok",
    "Beijing",
    "Beirut",
    "Buenos Aires",
    "Cairo",
    "Cape Town",
    "Casablanca",
    "Chicago",
    "Delhi",
    "Dubai",
    "Istanbul",
    "Jakarta",
    "Johannesburg",
    "Kuala Lumpur",
    "Las Vegas",
    "Los Angeles",
    "Manila",
    "Melbourne",
    "Mexico City",
    "Miami",
    "Moscow",
    "Mumbai",
    "Nairobi",
    "New Delhi",
    "New York City",
    "Osaka",
    "Ottawa",
    "Panama City",
    "Perth",
    "Phnom Penh",
    "Rio de Janeiro",
    "Riyadh",
    "San Francisco",
    "Santiago",
    "Sao Paulo",
    "Seoul",
    "Shanghai",
    "Singapore",
    "Sydney",
    "Taipei",
    "Tokyo",
    "Toronto",
    "Vancouver",
    "Washington, D.C.",
    "Wellington",
    "Yangon",
    "Almaty",
    "Antananarivo",
    "Ashgabat",
    "Asmara",
    "Baku",
    "Bamako",
    "Bandar Seri Begawan",
    "Bishkek",
    "Brasilia",
    "Bujumbura",
    "Conakry",
    "Dakar",
    "Damascus",
    "Dhaka",
    "Dodoma",
    "Doha",
    "Gaborone",
    "Georgetown",
    "Hanoi",
    "Harare",
    "Havana",
    "Hobart",
    "Islamabad",
    "Kabul",
    "Kampala",
    "Kathmandu",
    "Kigali",
    "Kingston",
    "Kingstown",
    "Kinshasa",
    "Kuwait City",
    "La Paz",
    "Libreville",
    "Lilongwe",
    "Lima",
    "Lobamba",
    "Lome",
    "Luanda",
    "Lusaka",
    "Majuro",
    "Malabo",
    "Male",
    "Managua",
    "Manama",
    "Manaus",
    "Maputo",
    "Maseru",
    "Mbabane",
    "Minsk",
    "Mogadishu",
    "Monrovia",
    "Montevideo",
    "Moroni",
    "Muscat",
    "N'Djamena",
    "Nassau",
    "Naypyidaw",
    "Niamey",
    "Nicosia",
    "Nouakchott",
    "Noumea",
    "Nuku'alofa",
    "Nuuk",
    "Oranjestad",
    "Ouagadougou",
    "Pago Pago",
    "Palikir",
    "Paramaribo",
    "Port Louis",
    "Port Moresby",
    "Port-au-Prince",
    "Port of Spain",
    "Porto-Novo",
    "Praia",
    "Pretoria",
    "Putrajaya",
    "Pyongyang",
    "Quito",
    "Rabat",
    "Reykjavik",
    "Road Town",
    "Roseau",
    "Saint George's",
    "Saint John's",
    "San Jose",
    "San Juan",
    "San Marino",
    "San Salvador",
    "Sana'a",
    "Santa Fe",
    "Sao Tome",
    "Sarajevo",
    "Skopje",
    "Sofia",
    "Sri Jayawardenepura Kotte",
    "St. George's",
    "Sucre",
    "Sukhumi",
    "Suva",
    "Tarawa",
    "Tashkent",
    "Tbilisi",
    "Tegucigalpa",
    "Tehran",
    "Thimphu",
    "Tirana",
    "Tiraspol",
    "Tripoli",
    "Tskhinvali",
    "Tunis",
    "Ulaanbaatar",
    "Vaduz",
    "Vatican City",
    "Victoria",
    "Vientiane",
    "Windhoek",
    "Yamoussoukro",
    "Yaounde",
    "Yerevan",
    "Bucharest",
    "Cluj-Napoca",
  ];

export {cities};